FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
      vim \
      git \
      tar \
      wget \
      make \
      g++ \
      sudo \
      patch \
      build-essential \
      libssl-dev \
      uuid-dev \
      libgpgme11-dev \
      squashfs-tools \
      libopenmpi-dev \
      openssh-client

# -- Install Go
WORKDIR /tmp
ENV VERSION=1.11.1 OS=linux ARCH=amd64
RUN wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz
RUN sudo tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz

# -- Add docker user
ARG NB_USER=docker
ARG NB_UID=1000
RUN useradd -u $NB_UID -m $NB_USER && \
    echo 'docker ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
COPY kanamori.py /home/$NB_USER/kanamori.py
USER $NB_USER

# -- Set up Singularity 3.0.0
ENV GOPATH=/home/$NB_USER/go
ENV PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin

RUN mkdir -p $GOPATH/src/github.com/sylabs
WORKDIR $GOPATH/src/github.com/sylabs
RUN git clone https://github.com/sylabs/singularity.git --branch release-3.0
WORKDIR singularity

RUN go get -u -v github.com/golang/dep/cmd/dep

WORKDIR $GOPATH/src/github.com/sylabs/singularity
RUN ./mconfig
RUN make -C builddir
RUN sudo make -C builddir install

# -- Pull triqs image and run example script
WORKDIR /home/$NB_USER

RUN singularity pull docker://flatironinstitute/triqs
CMD mpirun -np 2 singularity exec triqs_latest.sif python kanamori.py
